# game constants
FPS = 60

# class constants

# asteroid constants
ASTEROID_SCALES = [40, 20, 10]
ASTEROID_SCORES = [20, 50, 100]
ASTEROID_SEGMENTS = 20
ASTEROID_SEGMENT_ANGLE_RANGE = 0.7
ASTEROID_SEGMENT_RANGE = 0.3
ASTEROID_SPIN_SPEED = 120
ASTEROID_SPEED = 150
ASTEROID_BULLET_IMPACT = 0.1
ASTEROID_IMPACT = 0.5
ASTEROID_SPLITS = 2
